[build]
# This is the directory to change to before starting a build.
base = "/"
command = "npm run build"
publish = "public/"

[[redirects]]
from = "/ingest/*"
to = "https://eu.posthog.com/:splat"
host = "eu.posthog.com"
status = 200
force = true
